# Generated by Django 3.1.2 on 2020-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=100, verbose_name='road')),
                ('zip_code', models.CharField(max_length=100, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complement')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
            ],
        ),
    ]
